fix: update npm to 6.14.9
We need to update `npm` as on older versions, there is an issue with how it interacts
with `graceful-fs`, manifesting in an esoteric error of `TypeError: cb.apply is not a function`.